sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: Dd9ZgcCStPCHzO8qgrF9RJePHnX6SSSAeb5vk71/v5PVytAnLzfU+F7ojFVuegg60pPWsyne52D9Wtf4xk/GSlsMIlI0jWV/GyROi/kiYWao+CMBD+cykHHeUo6kjqM9O8Mh8zorkkNgd8Sx/dmL4Njvdg6L7Te0Wv2CZzyLRPuktJJaTcPcrxLIA7+rNfulwpcvncrAdwuFx9SCBAvA5gdYCnK4FdryGIbJyKbWJ/500s0dC/2DisD2B3GG36cjpdxBpaaP8fM6sQR2kvBX9qyBmrBj8xFNiLiEPtdwAU8dQU51PtRLACmKMLQ/dbThXFDU7meDF0wkp4u7PgtP4jRrKz2e8n050TMdOluR9tFDyTp3X1A/bl/pLJh+8WxKofuzf/ui9R8xWVkGS6yNAUXn0m89Qn/cPFH+Ti+A9kZqV0IkhdP/7KwckdMj5vlME8BFHIeYaDiox8ZZQQqaiGmOZ9tJQwEoUlJTvh6y3KJ0EfI+FJiU4icwSlHurDJeTDJn402GAHXIQCzQQx5ypaSNsyTnq/gRl28h8t8hO0UO6Fl60PfmSq4HuTLPYYW11jvRwu9hGIU9CmZlNzreH+tcsmWwn/z1FI7Dk2UVj1pgmGYvoB2OOm0wEzaArSDMj3myG6dH3UfyD+oZHz1UGKPDCyJ0wP4wkvu6SqKJglM=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/Do-and-Dare---a-Brave-Boy-s-Fight-for-Fortune_5747
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy